apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: secretwatchers.example.com
spec:
  group: example.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                secretName:
                  type: string
            status:
              type: object
              properties:
                lastRotated:
                  type: string
                  format: date-time
  scope: Namespaced
  names:
    plural: secretwatchers
    singular: secretwatcher
    kind: SecretWatcher
    shortNames:
      - sw